### PR TITLE
Switch to formatted stylesheet

### PR DESCRIPTION
**Pull request by sornas**
- [x] Table of contents

### CODE REVIEW

**Review by FredTheDino — APPROVED** [review]
Looks sane to me - I'm gonna assume you did this correctly! <3

**Review by FredTheDino — APPROVED** [review]
I haven't read all of it - but LGTM.

Picture with how it looks so I don't have to build it?

**Review by EMattfolk — CHANGES_REQUESTED** [review]
There are some dividers that are not the right color. They should be darker.

**Comment by sornas** [comment]
image

**Review by EMattfolk — APPROVED** [review]

**Comment by FredTheDino** [comment]
image
These colors look off... :(

**Comment by EMattfolk** [comment]
> These colors look off... :( But that might be easier said than done.

It should be pretty easy to fix.

**Pull request merged**
