### PR TITLE
Rc drops

### PR DESCRIPTION
**Pull request by sornas**

### CODE REVIEW

**Comment by sornas** [comment]
This is on main (5cc372b):

```
running 10 tests
test rc::tests::as_ref ... ok
test rc::tests::explicit_drop ... ok
test rc::tests::from ... ok
test rc::tests::clone ... ok
test rc::tests::deref ... ok
test rc::tests::partial_eq ... ok
test rc::tests::new_empty ... ok
test rc::tests::partial_ord ... ok
test rc::tests::implicit_drop ... ok
test rc::tests::ord ... ok

test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 136 filtered out; finished in 0.20s

==133948==
==133948== HEAP SUMMARY:
==133948==     in use at exit: 208 bytes in 15 blocks
==133948==   total heap usage: 887 allocs, 872 frees, 106,775 bytes allocated
==133948==
==133948== LEAK SUMMARY:
==133948==    definitely lost: 208 bytes in 15 blocks
==133948==    indirectly lost: 0 bytes in 0 blocks
==133948==      possibly lost: 0 bytes in 0 blocks
==133948==    still reachable: 0 bytes in 0 blocks
==133948==         suppressed: 0 bytes in 0 blocks
==133948== Rerun with --leak-check=full to see details of leaked memory
==133948==
==133948== For lists of detected and suppressed errors, rerun with: -s
==133948== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

And this is on this branch (fa63e24):

```
running 11 tests
test rc::tests::clone ... ok
test rc::tests::as_ref ... ok
test rc::tests::deref ... ok
test rc::tests::explicit_drop ... ok
test rc::tests::implicit_drop ... ok
test rc::tests::from ... ok
test rc::tests::calls_drop ... ok
test rc::tests::partial_ord ... ok
test rc::tests::ord ... ok
test rc::tests::new_empty ... ok
test rc::tests::partial_eq ... ok

test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 136 filtered out; finished in 0.21s

==134874==
==134874== HEAP SUMMARY:
==134874==     in use at exit: 0 bytes in 0 blocks
==134874==   total heap usage: 915 allocs, 915 frees, 108,730 bytes allocated
==134874==
==134874== All heap blocks were freed -- no leaks are possible
==134874==
==134874== For lists of detected and suppressed errors, rerun with: -s
==134874== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Review by FredTheDino — APPROVED** [review]
Nice new test! Always great with more coverage!

**Comment by FredTheDino** [comment]
> Basically, we're currently leaking memory. And applying the fix as done here kills our performance gains over `std::rc::Rc`.
> 
> This is on main (5cc372b):
> 
> ```
> running 10 tests
> test rc::tests::as_ref ... ok
> test rc::tests::explicit_drop ... ok
> test rc::tests::from ... ok
> test rc::tests::clone ... ok
> test rc::tests::deref ... ok
> test rc::tests::partial_eq ... ok
> test rc::tests::new_empty ... ok
> test rc::tests::partial_ord ... ok
> test rc::tests::implicit_drop ... ok
> test rc::tests::ord ... ok
> 
> test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 136 filtered out; finished in 0.20s
> 
> ==133948==
> ==133948== HEAP SUMMARY:
> ==133948==     in use at exit: 208 bytes in 15 blocks
> ==133948==   total heap usage: 887 allocs, 872 frees, 106,775 bytes allocated
> ==133948==
> ==133948== LEAK SUMMARY:
> ==133948==    definitely lost: 208 bytes in 15 blocks
> ==133948==    indirectly lost: 0 bytes in 0 blocks
> ==133948==      possibly lost: 0 bytes in 0 blocks
> ==133948==    still reachable: 0 bytes in 0 blocks
> ==133948==         suppressed: 0 bytes in 0 blocks
> ==133948== Rerun with --leak-check=full to see details of leaked memory
> ==133948==
> ==133948== For lists of detected and suppressed errors, rerun with: -s
> ==133948== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> ```
> 
> And this is on this branch (fa63e24):
> 
> ```
> running 11 tests
> test rc::tests::clone ... ok
> test rc::tests::as_ref ... ok
> test rc::tests::deref ... ok
> test rc::tests::explicit_drop ... ok
> test rc::tests::implicit_drop ... ok
> test rc::tests::from ... ok
> test rc::tests::calls_drop ... ok
> test rc::tests::partial_ord ... ok
> test rc::tests::ord ... ok
> test rc::tests::new_empty ... ok
> test rc::tests::partial_eq ... ok
> 
> test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 136 filtered out; finished in 0.21s
> 
> ==134874==
> ==134874== HEAP SUMMARY:
> ==134874==     in use at exit: 0 bytes in 0 blocks
> ==134874==   total heap usage: 915 allocs, 915 frees, 108,730 bytes allocated
> ==134874==
> ==134874== All heap blocks were freed -- no leaks are possible
> ==134874==
> ==134874== For lists of detected and suppressed errors, rerun with: -s
> ==134874== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> ```

I apparently missed this comment. But it makes sense that we didn't free the vectors? I'm just guessing tbh. How hard is the performance drop? Do we get the same performance as std::RC?

**Comment by FredTheDino** [comment]
I ran some tests:
```
Rc:
Benchmark #1: ./target/release/sylt fib.sy
  Time (mean ± σ):     891.9 ms ±  60.4 ms    [User: 884.2 ms, System: 1.5 ms]
  Range (min … max):   835.1 ms … 1377.9 ms    200 runs

Rc - RcMut:
Benchmark #1: ./target/release/sylt fib.sy
  Time (mean ± σ):     876.5 ms ±  68.1 ms    [User: 866.3 ms, System: 2.0 ms]
  Range (min … max):   817.5 ms … 1395.6 ms    200 runs

Base:
Benchmark #1: ./target/release/sylt fib.sy
  Time (mean ± σ):     887.8 ms ±  48.9 ms    [User: 880.7 ms, System: 1.5 ms]
  Range (min … max):   839.2 ms … 1129.6 ms    200 runs
```

It's hard to know for sure what is what - but you get a lot of noise in the readings. I ran `fib(30)` - which took around 1s for each test on my machine

**Pull request merged**
